<?php

/**
 * Definisi menu aplikasi (label, struktur, pemetaan izin halaman).
 * Disertakan oleh header dan halaman hub menu.
 */
return [
    'menuItems' => [
        '/pwa_nailulmuna/dashboard.php' => 'Dashboard',
        '/pwa_nailulmuna/santri/semua_jati.php' => 'Data induk santri',
        '/pwa_nailulmuna/santri/riwayat.php' => 'Riwayat santri',
        '/pwa_nailulmuna/santri/hidmah.php' => 'Input hidmah',
        '/pwa_nailulmuna/santri/index.php' => 'Santri Aktif',
        '/pwa_nailulmuna/santri/create.php' => 'Tambah santri',
        '/pwa_nailulmuna/santri/keluar.php' => 'Administrasi keluar',
        '/pwa_nailulmuna/data/wali.php' => 'Wali santri',
        '/pwa_nailulmuna/pembimbing/index.php' => 'Data pembimbing',
        '/pwa_nailulmuna/pembimbing/perizinan.php' => 'Izin pembimbing',
        '/pwa_nailulmuna/presensi/scan.php' => 'Scan Presensi',
        '/pwa_nailulmuna/jadwal/index.php' => 'Jadwal',
        '/pwa_nailulmuna/akademik/hafalan.php' => 'Setoran Hafalan',
        '/pwa_nailulmuna/akademik/bait_kitab.php' => 'Pengaturan bait',
        '/pwa_nailulmuna/akademik/kalender.php' => 'Kalender akademik',
        '/pwa_nailulmuna/settings/kalender.php' => 'Kalender libur',
        '/pwa_nailulmuna/settings/hijri_mappings.php' => 'Pemetaan Hijriyah',
        '/pwa_nailulmuna/akademik/rapor.php' => 'Rapor Akademik',
        '/pwa_nailulmuna/santri/mukimin.php' => 'Data Mukimin',
        '/pwa_nailulmuna/settings/akses_mukimin.php' => 'Akses Portal Mukimin',
        '/pwa_nailulmuna/settings/pesantren.php' => 'Pesantren',
        '/pwa_nailulmuna/settings/peraturan.php' => 'Peraturan poin',
        '/pwa_nailulmuna/settings/tingkatan.php' => 'Master tingkatan',
        '/pwa_nailulmuna/settings/kamar_ranjang.php' => 'Kamar & ranjang',
        '/pwa_nailulmuna/settings/kelas_ruangan.php' => 'Ruangan kelas',
        '/pwa_nailulmuna/perizinan/permohonan.php' => 'Permohonan Izin',
        '/pwa_nailulmuna/perizinan/index.php' => 'Perizinan',
        '/pwa_nailulmuna/perizinan/izin_tetap.php' => 'Izin Tetap Hidmah',
        '/pwa_nailulmuna/admin/surat_nomor.php' => 'Nomor surat',
        '/pwa_nailulmuna/admin/cek_update.php' => 'Cek update sistem',
        '/pwa_nailulmuna/admin/rekap_surat_izin.php' => 'Rekap surat izin',
        '/pwa_nailulmuna/admin/rekap_surat_sp.php' => 'Rekap surat SP',
        '/pwa_nailulmuna/rekap/santri_bagus.php' => 'Rekap Keaktifan Santri',
        '/pwa_nailulmuna/rekap/index.php' => 'Rekap Presensi',
        '/pwa_nailulmuna/poin/input.php' => 'Input Poin',
        '/pwa_nailulmuna/poin/rekap.php' => 'Rekap Poin',
        '/pwa_nailulmuna/poin/settings.php' => 'Peraturan poin',
        '/pwa_nailulmuna/keuangan/index.php' => 'Dashboard Keuangan',
        '/pwa_nailulmuna/keuangan/neraca.php' => 'Neraca',
        '/pwa_nailulmuna/keuangan/arus-kas.php' => 'Arus Kas',
        '/pwa_nailulmuna/keuangan/pembayaran.php' => 'Input Pembayaran',
        '/pwa_nailulmuna/keuangan/pemasukan.php' => 'Pemasukan Lain',
        '/pwa_nailulmuna/keuangan/pengeluaran.php' => 'Input Pengeluaran',
        '/pwa_nailulmuna/keuangan/talangan.php' => 'Dana Talangan',
        '/pwa_nailulmuna/keuangan/potongan_syahriyah.php' => 'Potongan Syahriyah',
        '/pwa_nailulmuna/keuangan/inventaris.php' => 'Inventaris Aset',
        '/pwa_nailulmuna/keuangan/pengaturan.php' => 'Pengaturan Keuangan',
        '/pwa_nailulmuna/keuangan/cashless_scan.php' => 'Top Up Cashless',
        '/pwa_nailulmuna/keuangan/cashless_pin.php' => 'Cashless & Uang Saku',
        '/pwa_nailulmuna/pembayaran/tagihan_syahriyah.php' => 'Tagihan Bulanan',
        '/pwa_nailulmuna/pembayaran/riwayat.php' => 'Riwayat Pembayaran',
        '/pwa_nailulmuna/pembayaran/laporan.php' => 'Laporan Syahriyah',
        '/pwa_nailulmuna/pembayaran/rekap_pos.php' => 'Rekap per POS',
        '/pwa_nailulmuna/rekap/pembimbing.php' => 'Rekap keaktifan pembimbing',
        '/pwa_nailulmuna/settings/kelas_keuangan.php' => 'Kelas keuangan',
        '/pwa_nailulmuna/rekap/izin_telat.php' => 'Rekap Telat',
        '/pwa_nailulmuna/settings/index.php' => 'Pesantren',
        '/pwa_nailulmuna/settings/admin.php' => 'Kelola Akses User',
    ],
    'menuStructure' => [
        ['type' => 'item', 'path' => '/pwa_nailulmuna/dashboard.php', 'icon' => 'fa-solid fa-house'],
        ['type' => 'group', 'id' => 'menu-grp-sdm', 'label' => 'Manajemen SDM', 'icon' => 'fa-solid fa-address-card', 'sections' => [
            ['title' => 'Santri', 'paths' => [
                '/pwa_nailulmuna/santri/semua_jati.php',
                '/pwa_nailulmuna/santri/index.php',
                '/pwa_nailulmuna/santri/mukimin.php',
                '/pwa_nailulmuna/santri/hidmah.php',
            ]],
            ['title' => 'Wali santri', 'paths' => [
                '/pwa_nailulmuna/data/wali.php',
                '/pwa_nailulmuna/settings/akses_mukimin.php',
            ]],
            ['title' => 'Pembimbing', 'paths' => [
                '/pwa_nailulmuna/pembimbing/index.php',
                '/pwa_nailulmuna/rekap/pembimbing.php',
            ]],
        ]],
        ['type' => 'group', 'id' => 'menu-grp-keuangan', 'label' => 'Keuangan', 'icon' => 'fa-solid fa-wallet', 'sections' => [
            ['title' => '', 'paths' => [
                '/pwa_nailulmuna/keuangan/index.php',
            ]],
            ['title' => 'Laporan', 'paths' => [
                '/pwa_nailulmuna/keuangan/neraca.php',
                '/pwa_nailulmuna/keuangan/arus-kas.php',
                '/pwa_nailulmuna/pembayaran/rekap_pos.php',
                '/pwa_nailulmuna/pembayaran/laporan.php',
            ]],
            ['title' => 'Transaksi', 'paths' => [
                '/pwa_nailulmuna/keuangan/pembayaran.php',
                '/pwa_nailulmuna/pembayaran/tagihan_syahriyah.php',
                '/pwa_nailulmuna/pembayaran/riwayat.php',
                '/pwa_nailulmuna/keuangan/pemasukan.php',
                '/pwa_nailulmuna/keuangan/pengeluaran.php',
                '/pwa_nailulmuna/keuangan/talangan.php',
                '/pwa_nailulmuna/keuangan/potongan_syahriyah.php',
                '/pwa_nailulmuna/keuangan/cashless_scan.php',
                '/pwa_nailulmuna/rekap/pembimbing.php',
            ]],
            ['title' => 'Pengaturan', 'paths' => [
                '/pwa_nailulmuna/keuangan/pengaturan.php',
                '/pwa_nailulmuna/settings/kelas_keuangan.php',
                '/pwa_nailulmuna/keuangan/inventaris.php',
                '/pwa_nailulmuna/keuangan/cashless_pin.php',
            ]],
        ]],
        ['type' => 'group', 'id' => 'menu-grp-perizinan', 'label' => 'Perizinan', 'icon' => 'fa-solid fa-person-walking-arrow-right', 'sections' => [
            ['title' => 'Izin santri', 'paths' => [
                '/pwa_nailulmuna/perizinan/permohonan.php',
                '/pwa_nailulmuna/perizinan/index.php',
                '/pwa_nailulmuna/perizinan/izin_tetap.php',
            ]],
            ['title' => 'Surat & rekap', 'paths' => [
                '/pwa_nailulmuna/admin/surat_nomor.php',
                '/pwa_nailulmuna/admin/rekap_surat_izin.php',
                '/pwa_nailulmuna/admin/rekap_surat_sp.php',
            ]],
            ['title' => 'Sistem', 'paths' => [
                '/pwa_nailulmuna/admin/cek_update.php',
            ]],
        ]],
        ['type' => 'group', 'id' => 'menu-grp-kajian', 'label' => 'Kajian', 'icon' => 'fa-solid fa-book-open', 'sections' => [
            ['title' => 'Jadwal & presensi', 'paths' => [
                '/pwa_nailulmuna/jadwal/index.php',
                '/pwa_nailulmuna/presensi/scan.php',
                '/pwa_nailulmuna/rekap/index.php',
                '/pwa_nailulmuna/rekap/izin_telat.php',
            ]],
            ['title' => 'Akademik', 'paths' => [
                '/pwa_nailulmuna/akademik/hafalan.php',
                '/pwa_nailulmuna/akademik/bait_kitab.php',
                '/pwa_nailulmuna/akademik/kalender.php',
                '/pwa_nailulmuna/akademik/rapor.php',
            ]],
            ['title' => 'Poin & keaktifan', 'paths' => [
                '/pwa_nailulmuna/poin/input.php',
                '/pwa_nailulmuna/poin/rekap.php',
                '/pwa_nailulmuna/rekap/santri_bagus.php',
            ]],
        ]],
        ['type' => 'group', 'id' => 'menu-grp-pengaturan', 'label' => 'Pengaturan', 'icon' => 'fa-solid fa-sliders', 'sections' => [
            ['title' => 'Umum', 'paths' => [
                '/pwa_nailulmuna/settings/pesantren.php',
                '/pwa_nailulmuna/settings/peraturan.php',
            ]],
            ['title' => 'Master data', 'paths' => [
                '/pwa_nailulmuna/settings/kalender.php',
                '/pwa_nailulmuna/settings/tingkatan.php',
                '/pwa_nailulmuna/settings/kamar_ranjang.php',
                '/pwa_nailulmuna/settings/kelas_ruangan.php',
                '/pwa_nailulmuna/settings/kelas_keuangan.php',
            ]],
            ['title' => 'Akses', 'paths' => [
                '/pwa_nailulmuna/settings/admin.php',
            ]],
        ]],
    ],
    'pengaturanNav' => [
        ['path' => '/pwa_nailulmuna/settings/pesantren.php', 'label' => 'Pesantren', 'icon' => 'fa-solid fa-mosque'],
        ['path' => '/pwa_nailulmuna/settings/peraturan.php', 'label' => 'Peraturan poin', 'icon' => 'fa-solid fa-scale-balanced'],
        ['path' => '/pwa_nailulmuna/settings/kalender.php', 'label' => 'Kalender libur', 'icon' => 'fa-solid fa-calendar-days'],
        ['path' => '/pwa_nailulmuna/settings/hijri_mappings.php', 'label' => 'Pemetaan Hijriyah', 'icon' => 'fa-solid fa-moon'],
        ['path' => '/pwa_nailulmuna/settings/tingkatan.php', 'label' => 'Master tingkatan', 'icon' => 'fa-solid fa-layer-group'],
        ['path' => '/pwa_nailulmuna/settings/kamar_ranjang.php', 'label' => 'Kamar & ranjang', 'icon' => 'fa-solid fa-bed'],
        ['path' => '/pwa_nailulmuna/settings/kelas_ruangan.php', 'label' => 'Ruangan kelas', 'icon' => 'fa-solid fa-door-open'],
        ['path' => '/pwa_nailulmuna/settings/kelas_keuangan.php', 'label' => 'Kelas keuangan', 'icon' => 'fa-solid fa-coins'],
        ['path' => '/pwa_nailulmuna/settings/admin.php', 'label' => 'Kelola akses', 'icon' => 'fa-solid fa-user-shield'],
        ['path' => '/pwa_nailulmuna/settings/push.php', 'label' => 'Push FCM', 'icon' => 'fa-solid fa-bell'],
    ],
    'permissionPathMap' => [
        '/pwa_nailulmuna/dashboard.php' => 'dashboard',
        '/pwa_nailulmuna/santri/index.php' => 'santri_index',
        '/pwa_nailulmuna/santri/mukimin.php' => 'santri_index',
        '/pwa_nailulmuna/santri/mukimin_export.php' => 'santri_index',
        '/pwa_nailulmuna/santri/mukimin_import.php' => 'santri_import',
        '/pwa_nailulmuna/santri/keluar.php' => 'santri_index',
        '/pwa_nailulmuna/santri/keluar_kekurangan_print.php' => 'santri_index',
        '/pwa_nailulmuna/santri/surat_keluar.php' => 'santri_index',
        '/pwa_nailulmuna/santri/surat_tanggungan.php' => 'santri_index',
        '/pwa_nailulmuna/santri/semua_jati.php' => 'santri_index',
        '/pwa_nailulmuna/santri/riwayat.php' => 'santri_index',
        '/pwa_nailulmuna/santri/hidmah.php' => 'santri_index',
        '/pwa_nailulmuna/santri/nonaktif_cepat.php' => 'santri_index',
        '/pwa_nailulmuna/santri/export_excel.php' => 'santri_index',
        '/pwa_nailulmuna/santri/alumni.php' => 'santri_index',
        '/pwa_nailulmuna/santri/alumni_export.php' => 'santri_index',
        '/pwa_nailulmuna/santri/alumni_import.php' => 'santri_import',
        '/pwa_nailulmuna/santri/muqim_boyong.php' => 'santri_index',
        '/pwa_nailulmuna/santri/create.php' => 'santri_create',
        '/pwa_nailulmuna/santri/edit.php' => 'santri_index',
        '/pwa_nailulmuna/santri/import.php' => 'santri_import',
        '/pwa_nailulmuna/pembimbing/edit.php' => 'pembimbing',
        '/pwa_nailulmuna/jadwal/edit.php' => 'jadwal',
        '/pwa_nailulmuna/perizinan/edit.php' => 'perizinan',
        '/pwa_nailulmuna/data/wali.php' => 'santri_index',
        '/pwa_nailulmuna/settings/akses_mukimin.php' => 'santri_index',
        '/pwa_nailulmuna/presensi/scan.php' => 'presensi_scan',
        '/pwa_nailulmuna/jadwal/index.php' => 'jadwal',
        '/pwa_nailulmuna/akademik/hafalan.php' => 'akademik_hafalan',
        '/pwa_nailulmuna/akademik/bait_kitab.php' => 'akademik_hafalan',
        '/pwa_nailulmuna/akademik/kalender.php' => 'akademik_hafalan',
        '/pwa_nailulmuna/akademik/rapor.php' => 'akademik_hafalan',
        '/pwa_nailulmuna/settings/pesantren.php' => 'pengaturan',
        '/pwa_nailulmuna/settings/peraturan.php' => 'pengaturan',
        '/pwa_nailulmuna/settings/kelas_ruangan.php' => 'pengaturan',
        '/pwa_nailulmuna/settings/kelas_keuangan.php' => 'pengaturan',
        '/pwa_nailulmuna/settings/tingkatan.php' => 'pengaturan',
        '/pwa_nailulmuna/settings/kamar_ranjang.php' => 'pengaturan',
        '/pwa_nailulmuna/settings/index.php' => 'pengaturan',
        '/pwa_nailulmuna/settings/kalender.php' => 'pengaturan',
        '/pwa_nailulmuna/settings/push.php' => 'pengaturan',
        '/pwa_nailulmuna/settings/hijri_mappings.php' => 'pengaturan',
        '/pwa_nailulmuna/perizinan/index.php' => 'perizinan',
        '/pwa_nailulmuna/perizinan/izin_tetap.php' => 'perizinan',
        '/pwa_nailulmuna/perizinan/kembali.php' => 'perizinan_scan',
        '/pwa_nailulmuna/perizinan/permohonan.php' => 'perizinan_permohonan',
        '/pwa_nailulmuna/admin/surat_nomor.php' => 'perizinan',
        '/pwa_nailulmuna/admin/rekap_surat_izin.php' => 'perizinan',
        '/pwa_nailulmuna/admin/rekap_surat_sp.php' => 'perizinan',
        '/pwa_nailulmuna/pembimbing/index.php' => 'pembimbing',
        '/pwa_nailulmuna/pembimbing/presensi.php' => 'presensi_scan',
        '/pwa_nailulmuna/pembimbing/perizinan.php' => 'pembimbing_perizinan',
        '/pwa_nailulmuna/rekap/santri_bagus.php' => 'rekap_keaktifan',
        '/pwa_nailulmuna/rekap/index.php' => 'rekap',
        '/pwa_nailulmuna/rekap/izin_telat.php' => 'rekap_telat',
        '/pwa_nailulmuna/rekap/pembimbing.php' => 'rekap_pembimbing',
        '/pwa_nailulmuna/poin/input.php' => 'poin_input',
        '/pwa_nailulmuna/poin/rekap.php' => 'poin_rekap',
        '/pwa_nailulmuna/poin/settings.php' => 'pengaturan',
        '/pwa_nailulmuna/keuangan/index.php' => 'keuangan',
        '/pwa_nailulmuna/keuangan/pembayaran.php' => 'keuangan',
        '/pwa_nailulmuna/keuangan/pemasukan.php' => 'keuangan',
        '/pwa_nailulmuna/keuangan/pengaturan.php' => 'keuangan',
        '/pwa_nailulmuna/keuangan/pengeluaran.php' => 'keuangan',
        '/pwa_nailulmuna/keuangan/talangan.php' => 'keuangan',
        '/pwa_nailulmuna/keuangan/potongan_syahriyah.php' => 'keuangan',
        '/pwa_nailulmuna/keuangan/inventaris.php' => 'keuangan',
        '/pwa_nailulmuna/keuangan/index.php?tab=a' => 'keuangan',
        '/pwa_nailulmuna/keuangan/index.php?tab=b' => 'keuangan',
        '/pwa_nailulmuna/keuangan/index.php?tab=c' => 'keuangan',
        '/pwa_nailulmuna/keuangan/index.php?tab=e' => 'keuangan',
        '/pwa_nailulmuna/keuangan/index.php?tab=f' => 'keuangan',
        '/pwa_nailulmuna/keuangan/index.php?tab=g' => 'keuangan',
        '/pwa_nailulmuna/keuangan/index.php?tab=h' => 'keuangan',
        '/pwa_nailulmuna/keuangan/index.php?tab=i' => 'keuangan',
        '/pwa_nailulmuna/keuangan/neraca.php' => 'keuangan',
        '/pwa_nailulmuna/keuangan/arus-kas.php' => 'keuangan',
        '/pwa_nailulmuna/keuangan/index.php?tab=j' => 'keuangan',
        '/pwa_nailulmuna/keuangan/inventaris.php' => 'keuangan',
        '/pwa_nailulmuna/keuangan/index.php?tab=k' => 'keuangan',
        '/pwa_nailulmuna/keuangan/cashless_scan.php' => 'keuangan_cashless_scan',
        '/pwa_nailulmuna/keuangan/cashless_pin.php' => 'pengaturan',
        '/pwa_nailulmuna/pembayaran/index.php' => 'keuangan',
        '/pwa_nailulmuna/keuangan/index.php?tab=i' => 'keuangan',
        '/pwa_nailulmuna/pembayaran/tagihan_syahriyah.php' => 'keuangan',
        '/pwa_nailulmuna/pembayaran/riwayat.php' => 'keuangan',
        '/pwa_nailulmuna/pembayaran/laporan.php' => 'keuangan',
        '/pwa_nailulmuna/pembayaran/rekap_pos.php' => 'keuangan',
        '/pwa_nailulmuna/settings/admin.php' => 'settings_admin',
    ],
];
