<?php

/**
 * Definisi menu aplikasi (label, struktur, pemetaan izin halaman).
 * Disertakan oleh header dan halaman hub menu.
 */
require_once __DIR__ . '/../helpers/user_permissions.php';

$__currentRoleForMenu = strtolower((string) ($_SESSION['user']['role'] ?? ''));
$__isSuperAdminForMenu = (int) ($_SESSION['user']['is_super_admin'] ?? 0) === 1;

// Struktur menu khusus untuk role pembimbing — sederhana, hanya berisi
// modul yang relevan dengan tugas pembimbing (dashboard, tugas/penilaian,
// izin pembimbing). Tidak menampilkan keuangan, gaji, yayasan, dll.
if ($__currentRoleForMenu === 'pembimbing' && !$__isSuperAdminForMenu) {
    return [
        'menuItems' => [
            '/pembimbing/dashboard.php' => 'Dashboard Pembimbing',
            '/presensi/scan.php' => 'Scan Presensi',
            '/pembimbing/tugas/index.php' => 'Daftar Tugas Ikhtibar',
            '/pembimbing/tugas_yayasan.php' => 'Tugas Yayasan (Timeline)',
            '/pembimbing/tugas/buat.php' => 'Buat Tugas / Soal',
            '/pembimbing/tugas/nilai.php' => 'Penilaian Tugas',
            '/pembimbing/tugas/rekap.php' => 'Rekap Nilai Ikhtibar',
            '/pembimbing/nilai_manual.php' => 'Nilai Manual',
            '/pembimbing/perizinan.php' => 'Atur Kegiatan Hari Ini',
            '/jadwal/index.php' => 'Jadwal Kegiatan',
            '/settings/profil.php' => 'Profil & Password',
        '/settings/akses_saya.php' => 'Hak Akses Saya',
        '/catatan/index.php' => 'Buku Catatan',
            '/pembimbing/setoran_dashboard.php' => 'Portal Setoran Hafalan',
        ],
        'menuStructure' => [
            ['type' => 'item', 'path' => '/pembimbing/dashboard.php', 'icon' => 'fa-solid fa-house'],
            ['type' => 'item', 'path' => '/presensi/scan.php', 'icon' => 'fa-solid fa-qrcode'],
            ['type' => 'group', 'id' => 'menu-grp-pb', 'label' => 'Pembimbing', 'expand' => true, 'icon' => 'fa-solid fa-chalkboard-user', 'sections' => [
                ['title' => 'Tugas & Jadwal', 'paths' => [
                    '/pembimbing/tugas/index.php',
                    '/pembimbing/tugas_yayasan.php',
                    '/pembimbing/tugas/rekap.php',
                    '/pembimbing/nilai_manual.php',
                    '/pembimbing/perizinan.php',
                    '/jadwal/index.php',
                    '/settings/profil.php',
                    '/catatan/index.php',
                    '/pembimbing/setoran_dashboard.php',
                ]],
            ]],
        ],
        'pengaturanNav' => [],
        'permissionPathMap' => user_permission_path_map(),
    ];
}

return [
    'menuItems' => [
        '/dashboard.php' => 'Dashboard',
        '/santri/semua_jati.php' => 'Data induk santri',
        '/santri/riwayat.php' => 'Riwayat santri',
        '/santri/tingkatan_ta.php' => 'Tingkatan per TA',
        '/santri/hidmah.php' => 'Input Hidmah',
        '/santri/index.php' => 'Data Santri',
        '/santri/create.php' => 'Tambah santri',
        '/santri/keluar.php' => 'Administrasi keluar',
        '/santri/mukimin.php' => 'Data Mukimin',
        '/santri/import.php' => 'Import Santri',
        '/data/wali.php' => 'Wali Santri',
        '/pembimbing/index.php' => 'Data Pembimbing',
        '/pembimbing/dashboard.php' => 'Dashboard Pembimbing',
        '/pembimbing/perizinan.php' => 'Izin pembimbing',
        '/presensi/scan.php' => 'Scan Presensi',
        '/presensi/kegiatan_khusus.php' => 'Kegiatan Khusus (Sekali Pakai)',
        '/presensi/rekap_tanpa_scan.php' => 'Jadwal Tanpa Scan',
        '/jadwal/index.php' => 'Jadwal',
        '/jadwal/kegiatan.php' => 'Kegiatan (Ta\'lim / Jama\'ah)',
        '/jadwal/import.php' => 'Import Jadwal',
        '/jadwal/edit.php' => 'Edit Jadwal',
        '/rekap/keaktivan_sdm.php' => 'Keaktivan SDM (Pembimbing & Munawib)',
        '/rekap/keaktifan_hari.php' => 'Keaktifan Hari Ini',
        '/rekap/munawib.php' => 'Laporan Munawib',
        '/rekap/kegiatan_khusus.php' => 'Rekap Kegiatan Khusus',
        '/pembimbing/munawib.php' => 'Data Munawib',
        '/akademik/hafalan.php' => 'Setoran Hafalan',
        '/akademik/setoran.php' => 'Setoran Hafalan (Hub)',
        '/akademik/setoran_dashboard.php' => 'Dashboard Setoran',
        '/pembimbing/setoran_dashboard.php' => 'Portal Setoran',
        '/pembimbing/setoran.php' => 'Scan Setoran',
        '/akademik/setoran_rekap.php' => 'Rekap Setoran',
        '/akademik/setoran_rekap_kitab.php' => 'Rekap Setoran per Kitab',
        '/akademik/setoran_penerima.php' => 'Penerima Setoran',
        '/akademik/bait_kitab.php' => 'Pengaturan Bait',
        '/akademik/kalender.php' => 'Kalender Akademik',
        '/settings/kalender.php' => 'Kalender Pondok',
        '/settings/kalender_ta.php' => 'Kalender & TA (Hub)',
        '/settings/hijri_mappings.php' => 'Kalender Hijriyah & Masehi',
        '/akademik/rapor.php' => 'Rapor Pesantren',
        '/akademik/skbt.php' => 'SKBT',
        '/pembimbing/tugas/index.php' => 'Tugas Ikhtibar (Pembimbing)',
        '/akademik/ikhtibar.php' => 'Tugas Ikhtibar (Hub)',
        '/pembimbing/tugas/buat.php' => 'Buat Tugas Ikhtibar',
        '/pembimbing/tugas/nilai.php' => 'Penilaian Tugas Ikhtibar',
        '/pembimbing/tugas/rekap.php' => 'Rekap Nilai Ikhtibar',
        '/pembimbing/nilai_manual.php' => 'Nilai Manual',
        '/akademik/ikhtibar_rekap.php' => 'Rekap Tugas Ikhtibar',
        '/settings/akses_mukimin.php' => 'Akses Portal Mukimin',
        '/settings/pesantren.php' => 'Pesantren',
        '/settings/surat_cetak.php' => 'Kop & Template Surat',
        '/settings/wa_otomatis.php' => 'WA Otomatis',
        '/settings/wa_laporan_kelas_kosong.php' => 'Laporan WA Kelas Kosong',
        '/settings/peraturan.php' => 'Peraturan Poin',
        '/settings/perizinan.php' => 'Pengaturan alur izin',
        '/settings/tingkatan.php' => 'Tingkatan & PKPPS',
        '/settings/kamar_ranjang.php' => 'Kamar & Ranjang',
        '/settings/kelas_ruangan.php' => 'Ruangan Kelas',
        '/perizinan/permohonan.php' => 'Pengajuan Izin',
        '/perizinan/hub.php' => 'Perizinan Santri (Hub)',
        '/perizinan/index.php' => 'Persetujuan Izin',
        '/perizinan/rekap_aktif.php' => 'Rekap Izin Aktif',
        '/perizinan/izin_tetap.php' => 'Izin Tetap Hidmah',
        '/perizinan/izin_rombongan.php' => 'Izin Rombongan',
        '/admin/surat_nomor.php' => 'Nomor Surat',
        '/admin/cek_update.php' => 'Cek Update Sistem',
        '/admin/rekap_surat_izin.php' => 'Rekap Surat Izin',
        '/admin/rekap_surat_sp.php' => 'Rekap Surat SP',
        '/rekap/santri_bagus.php' => 'Rekap Keaktifan Santri',
        '/rekap/alpa_santri.php' => 'Laporan ALPA per Santri',
        '/pengasuh/dashboard.php' => 'Dashboard Pengasuh',
        '/pengasuh/laporan_hari.php' => 'Laporan Hari Ini',
        '/pengasuh/perizinan.php' => 'Persetujuan Izin Pengasuh',
        '/pengasuh/nilai_keaktifan.php' => 'Nilai Keaktifan Santri',
        '/rekap/index.php' => 'Rekap Presensi',
        '/rekap/presensi.php' => 'Rekap Presensi (Hub)',
        '/rekap/panduan.php' => 'Panduan Alur Presensi',
        '/poin/input.php' => 'Input Poin',
        '/poin/rekap.php' => 'Rekap Poin',
        '/keuangan/index.php' => 'Dashboard Keuangan',
        '/keuangan/transaksi.php' => 'Tagihan & Pembayaran',
        '/keuangan/kas.php' => 'Kas Umum',
        '/keuangan/cashless.php' => 'Cashless Koperasi',
        '/keuangan/neraca.php' => 'Neraca',
        '/keuangan/neraca-perbaikan.php' => 'Saran Perbaikan Neraca',
        '/keuangan/arus-kas.php' => 'Arus Kas',
        '/keuangan/rekap-kas-bulan.php' => 'Rekap Kas Bulanan',
        '/keuangan/perbaikan-kas.php' => 'Perbaikan Kas',
        '/keuangan/pembayaran.php' => 'Input Pembayaran',
        '/keuangan/tagihan_wali.php' => 'Tagihan Khusus ke Wali',
        '/keuangan/pemasukan.php' => 'Pemasukan Lain',
        '/keuangan/pengeluaran.php' => 'Input Pengeluaran',
        '/keuangan/riwayat_pengeluaran.php' => 'Riwayat Pengeluaran',
        '/keuangan/riwayat_pembayaran.php' => 'Riwayat Masuk & Keluar',
        '/keuangan/impor-ekspor.php' => 'Impor / Ekspor Excel',
        '/keuangan/talangan.php' => 'Dana Talangan',
        '/keuangan/potongan_syahriyah.php' => 'Potongan Syahriyah (per santri)',
        '/keuangan/inventaris.php' => 'Inventaris Aset',
        '/keuangan/pengaturan.php' => 'Pengaturan Keuangan',
        '/keuangan/panduan.php' => 'Panduan Alur Keuangan',
        '/keuangan/offline-data.php' => 'Data Offline Keuangan',
        '/keuangan/cashless_scan.php' => 'Top Up Cashless',
        '/keuangan/cashless_laporan.php' => 'Laporan Cashless Koperasi',
        '/keuangan/cashless_setor.php' => 'Setor Cashless Koperasi',
        '/keuangan/cashless_pin.php' => 'Rekap Saldo & PIN Cashless',
        '/pembayaran/tagihan_syahriyah.php' => 'Status Tagihan Bulanan',
        '/pembayaran/cek_pembayaran.php' => 'Cek Pembayaran',
        '/pembayaran/riwayat.php' => 'Riwayat Pembayaran',
        '/pembayaran/laporan.php' => 'Laporan Syahriyah',
        '/pembayaran/laporan_kopsa_per_santri.php' => 'KOPSA per Santri (per Bulan)',
        '/pembayaran/laporan_pkpps_syahriyah.php' => 'Laporan Syahriyah PKPPS',
        '/pembayaran/kartu_syahriyah_santri.php' => 'Kartu Syahriyah Santri',
        '/pkpps/santri.php' => 'Santri PKPPS',
        '/pkpps/import_santri.php' => 'Import Santri PKPPS',
        '/pkpps/jadwal.php' => 'Jadwal PKPPS',
        '/pkpps/import.php' => 'Import Jadwal PKPPS',
        '/pkpps/index.php' => 'Dashboard PKPPS',
        '/pkpps/hub.php' => 'PKPPS (Hub)',
        '/pkpps/tugas/index.php' => 'Tugas & Soal PKPPS',
        '/pkpps/tugas/buat.php' => 'Buat Tugas PKPPS',
        '/pkpps/tugas/nilai.php' => 'Nilai Tugas PKPPS',
        '/pkpps/tugas/rekap.php' => 'Rekap Tugas PKPPS',
        '/pkpps/rapor.php' => 'Rapor PKPPS',
        '/pkpps/pengaturan_rapor.php' => 'Pengaturan Rapor PKPPS',
        '/rekap/pkpps_keaktivan.php' => 'Keaktivan PKPPS',
        '/rekap/pkpps_keaktifan_hari.php' => 'Keaktifan PKPPS Hari Ini',
        '/settings/kelas_syahriyah.php' => 'Jenis Syahriyah (master)',
        '/pembayaran/rekap_pos.php' => 'Rekap per POS',
        '/rekap/pembimbing.php' => 'Payroll Pembimbing',
        '/settings/tarif_payroll.php' => 'Master Tarif Payroll',
        '/settings/kelas_keuangan.php' => 'Kelas Keuangan',
        '/settings/opsional_santri.php' => 'Makan & Saku per Santri',
        '/rekap/izin_telat.php' => 'Rekap Telat',
        '/settings/push.php' => 'Notifikasi & Lonceng',
        '/settings/admin.php' => 'Kelola Akses User',
        '/settings/portal_pembimbing.php' => 'Banner Portal Pembimbing',
        '/settings/presensi_data.php' => 'Kelola Data Presensi',
        '/yayasan/sdm.php' => 'SDM Musyawarah',
        '/yayasan/scan_musyawarah.php' => 'Scan Musyawarah',
        '/yayasan/pengurus.php' => 'Pengurus',
        '/yayasan/rapat.php' => 'Rapat & Musyawarah',
        '/yayasan/notulen.php' => 'Notulen',
        '/yayasan/timeline.php' => 'Timeline & Tugas',
        '/yayasan/operasional.php' => 'Yayasan',
        '/yayasan/pengawasan.php' => 'Dashboard Pengawasan',
        '/yayasan/ringkasan.php' => 'Yayasan — To-Do & Agenda',
        '/yayasan/ketertiban.php' => 'Menu Ketertiban',
        '/yayasan/kesehatan.php' => 'Laporan Kesehatan',
        '/yayasan/keaktifan.php' => 'Keaktifan Hari Ini',
        '/yayasan/keaktifan_ranking.php' => 'Ranking Keaktifan Tingkatan',
        '/yayasan/sdm_hari.php' => 'Keaktifan SDM Hari Ini',
        '/yayasan/executive.php' => 'Executive Summary',
        '/settings/profil.php' => 'Profil & Password',
        '/settings/akses_saya.php' => 'Hak Akses Saya',
        '/catatan/index.php' => 'Buku Catatan',
    ],
    'menuStructure' => [
        ['type' => 'item', 'path' => '/dashboard.php', 'icon' => 'fa-solid fa-house'],
        ['type' => 'group', 'id' => 'menu-grp-sdm', 'label' => 'Manajemen SDM', 'icon' => 'fa-solid fa-address-card', 'sections' => [
            ['title' => 'Santri', 'paths' => [
                '/santri/index.php',
                '/santri/import.php',
                '/santri/hidmah.php',
                '/santri/tingkatan_ta.php',
                '/santri/mukimin.php',
            ]],
            ['title' => 'Wali Santri', 'paths' => [
                '/data/wali.php',
            ]],
            ['title' => 'Pembimbing', 'paths' => [
                '/pembimbing/dashboard.php',
                '/pembimbing/index.php',
                '/pembimbing/perizinan.php',
            ]],
            ['title' => 'Munawib', 'paths' => [
                '/pembimbing/munawib.php',
                '/rekap/munawib.php',
            ]],
        ]],
        ['type' => 'group', 'id' => 'menu-grp-keuangan', 'label' => 'Keuangan', 'icon' => 'fa-solid fa-wallet', 'sections' => [
            ['title' => 'Ringkasan', 'paths' => [
                '/keuangan/index.php',
                '/keuangan/neraca.php',
                '/keuangan/neraca-perbaikan.php',
                '/keuangan/arus-kas.php',
                '/keuangan/rekap-kas-bulan.php',
                '/keuangan/offline-data.php',
                '/pembayaran/rekap_pos.php',
            ]],
            ['title' => 'Transaksi', 'paths' => [
                '/keuangan/transaksi.php',
                '/pembayaran/cek_pembayaran.php',
                '/keuangan/kas.php',
                '/keuangan/riwayat_pembayaran.php',
                '/keuangan/impor-ekspor.php',
                '/keuangan/perbaikan-kas.php',
                '/keuangan/cashless.php',
                '/keuangan/pengaturan.php?bagian=santri_bulanan&sub=potongan',
                '/keuangan/talangan.php',
            ]],
            ['title' => 'Laporan Syahriyah & Gaji', 'paths' => [
                '/pembayaran/laporan.php',
                '/pembayaran/kartu_syahriyah_santri.php',
                '/pembayaran/laporan_kopsa_per_santri.php',
                '/rekap/pembimbing.php',
            ]],
            ['title' => 'Pengaturan', 'paths' => [
                '/keuangan/pengaturan.php',
                '/keuangan/panduan.php',
                '/keuangan/cashless_pin.php',
                '/keuangan/inventaris.php',
                '/keuangan/pengaturan.php?bagian=santri_bulanan',
            ]],
        ]],
        ['type' => 'group', 'id' => 'menu-grp-pkpps', 'label' => 'PKPPS', 'icon' => 'fa-solid fa-graduation-cap', 'sections' => [
            ['title' => 'Program PKPPS', 'paths' => [
                '/pkpps/index.php',
                '/pkpps/rapor.php',
                '/pkpps/pengaturan_rapor.php',
            ]],
        ]],
        ['type' => 'group', 'id' => 'menu-grp-kajian', 'label' => 'Kajian & Presensi', 'icon' => 'fa-solid fa-book-open', 'sections' => [
            ['title' => 'Jadwal & Scan', 'paths' => [
                '/jadwal/index.php',
                '/jadwal/kegiatan.php',
                '/jadwal/import.php',
                '/presensi/scan.php',
                '/presensi/kegiatan_khusus.php',
                '/presensi/rekap_tanpa_scan.php',
            ]],
            ['title' => 'Rekap', 'paths' => [
                '/rekap/presensi.php',
            ]],
            ['title' => 'Setoran Hafalan', 'paths' => [
                '/akademik/setoran.php',
            ]],
            ['title' => 'Tugas & Ikhtibar', 'paths' => [
                '/akademik/ikhtibar.php',
                '/akademik/rapor.php',
                '/akademik/skbt.php',
            ]],
            ['title' => 'Poin & Keaktifan', 'paths' => [
                '/pengasuh/dashboard.php',
                '/pengasuh/laporan_hari.php',
                '/poin/input.php',
                '/poin/rekap.php',
                '/pengasuh/nilai_keaktifan.php',
            ]],
        ]],
        ['type' => 'group', 'id' => 'menu-grp-perizinan', 'label' => 'Perizinan', 'icon' => 'fa-solid fa-person-walking-arrow-right', 'sections' => [
            ['title' => 'Alur izin', 'paths' => [
                '/perizinan/hub.php',
            ]],
            ['title' => 'Surat & arsip', 'paths' => [
                '/admin/surat_nomor.php',
                '/admin/rekap_surat_izin.php',
                '/admin/rekap_surat_sp.php',
            ]],
        ]],
        ['type' => 'item', 'path' => '/yayasan/operasional.php', 'icon' => 'fa-solid fa-building-columns', 'match_prefix' => '/yayasan/'],
        ['type' => 'item', 'path' => '/catatan/index.php', 'icon' => 'fa-solid fa-book'],
        ['type' => 'group', 'id' => 'menu-grp-pengaturan', 'label' => 'Pengaturan', 'icon' => 'fa-solid fa-sliders', 'sections' => [
            ['title' => 'Umum', 'paths' => [
                '/settings/pesantren.php',
                '/settings/surat_cetak.php',
                '/settings/kalender_ta.php',
                '/settings/peraturan.php',
                '/settings/perizinan.php',
            ]],
            ['title' => 'WhatsApp Otomatis', 'paths' => [
                '/settings/wa_otomatis.php',
            ]],
            ['title' => 'Master Data', 'paths' => [
                '/settings/tingkatan.php',
                '/settings/kelas_keuangan.php',
                '/settings/kelas_syahriyah.php',
                '/settings/tarif_payroll.php',
                '/settings/kelas_ruangan.php',
                '/settings/kamar_ranjang.php',
            ]],
            ['title' => 'Akses & Sistem', 'paths' => [
                '/settings/admin.php',
                '/settings/portal_pembimbing.php',
                '/settings/akses_mukimin.php',
                '/settings/presensi_data.php',
                '/settings/push.php',
                '/admin/cek_update.php',
            ]],
        ]],
    ],
    'pengaturanNav' => [
        ['path' => '/settings/pesantren.php', 'label' => 'Profil Pondok', 'icon' => 'fa-solid fa-mosque', 'group' => 'Umum'],
        ['path' => '/settings/surat_cetak.php', 'label' => 'Kop & Template Surat', 'icon' => 'fa-solid fa-file-lines', 'group' => 'Umum'],
        ['path' => '/settings/kalender_ta.php', 'label' => 'Kalender & Tagihan TA', 'icon' => 'fa-solid fa-calendar-days', 'group' => 'Umum'],
        ['path' => '/settings/peraturan.php', 'label' => 'Peraturan Poin', 'icon' => 'fa-solid fa-scale-balanced', 'group' => 'Umum'],
        ['path' => '/settings/perizinan.php', 'label' => 'Pengaturan alur izin', 'icon' => 'fa-solid fa-person-walking-arrow-right', 'group' => 'Umum'],
        ['path' => '/settings/wa_otomatis.php', 'label' => 'WA Otomatis', 'icon' => 'fa-solid fa-comments', 'group' => 'WhatsApp'],
        ['path' => '/settings/tingkatan.php', 'label' => 'Tingkatan & PKPPS', 'icon' => 'fa-solid fa-layer-group', 'group' => 'Master Data'],
        ['path' => '/settings/kelas_keuangan.php', 'label' => 'Kelas Keuangan', 'icon' => 'fa-solid fa-coins', 'group' => 'Master Data'],
        ['path' => '/settings/kelas_syahriyah.php', 'label' => 'Jenis Syahriyah', 'icon' => 'fa-solid fa-hand-holding-dollar', 'group' => 'Master Data'],
        ['path' => '/settings/kelas_ruangan.php', 'label' => 'Ruangan Kelas', 'icon' => 'fa-solid fa-door-open', 'group' => 'Master Data'],
        ['path' => '/settings/kamar_ranjang.php', 'label' => 'Kamar & Ranjang', 'icon' => 'fa-solid fa-bed', 'group' => 'Master Data'],
        ['path' => '/settings/tarif_payroll.php', 'label' => 'Tarif Payroll', 'icon' => 'fa-solid fa-sack-dollar', 'group' => 'Master Data'],
        ['path' => '/keuangan/pengaturan.php?bagian=santri_bulanan&sub=opsional', 'label' => 'Makan & Saku per Santri', 'icon' => 'fa-solid fa-utensils', 'group' => 'Keuangan'],
        ['path' => '/settings/admin.php', 'label' => 'Kelola Akses User', 'icon' => 'fa-solid fa-user-shield', 'group' => 'Sistem'],
        ['path' => '/settings/portal_pembimbing.php', 'label' => 'Banner Portal Pembimbing', 'icon' => 'fa-solid fa-panorama', 'group' => 'Sistem'],
        ['path' => '/settings/akses_mukimin.php', 'label' => 'Akses Portal Mukimin', 'icon' => 'fa-solid fa-key', 'group' => 'Sistem'],
        ['path' => '/settings/presensi_data.php', 'label' => 'Kelola Data Presensi', 'icon' => 'fa-solid fa-database', 'group' => 'Sistem'],
        ['path' => '/settings/push.php', 'label' => 'Notifikasi & Lonceng', 'icon' => 'fa-solid fa-bell', 'group' => 'Sistem'],
        ['path' => '/admin/cek_update.php', 'label' => 'Cek Update Sistem', 'icon' => 'fa-solid fa-arrows-rotate', 'group' => 'Sistem'],
    ],
    'permissionPathMap' => user_permission_path_map(),
];
